# -*- coding: utf-8 -*-
"""
  run_parameters_init.py generated by WhatsOpt 1.9.3
"""
import numpy as np
from numpy import nan

def initialize(mda):

    mda['Ae'] = np.ones((1,))
    mda['beta'] = np.ones((1,))
    mda['De'] = np.ones((1,))
    mda['Dnozzle'] = 1.0
    mda['Ds'] = np.ones((1,))
    mda['Dt'] = np.ones((1,))
    mda['FF'] = 1.0
    mda['f_safety'] = 1.0
    mda['g0'] = np.ones((1,))
    mda['gamma'] = np.ones((1,))
    mda['k_sm'] = np.ones((1,))
    mda['Lfrust'] = 1.0
    mda['Lvehicle'] = np.ones((1,))
    mda['Mcarter'] = 1.0
    mda['Minsulation'] = 1.0
    mda['M_CaseBody'] = 1.0
    mda['M_CaseFrust'] = 1.0
    mda['M_CaseTop'] = 1.0
    mda['M_InsulationBody'] = 1.0
    mda['M_InsulationTop'] = 1.0
    mda['M_PL'] = np.ones((1,))
    mda['Pa'] = np.ones((1,))
    mda['Pc'] = np.ones((1,))
    mda['Pe'] = np.ones((1,))
    mda['R'] = np.ones((1,))
    mda['rho'] = 1.0
    mda['rho_in'] = 1.0
    mda['rho_p'] = 1.0
    mda['Ru'] = np.ones((1,))
    mda['SF'] = np.ones((1,))
    mda['sigma'] = 1.0
    mda['Sint'] = np.ones((1,))
    mda['t'] = 1.0
    mda['tb'] = np.ones((1,))
    mda['Tc'] = np.ones((1,))
    mda['theta_n'] = np.ones((1,))
    mda['zeta'] = np.ones((1,))



if __name__ == "__main__":
    from tabulate import tabulate

    mda = {}
    initialize(mda)
    headers = ["parameter", "value"]
    data = [[k, mda[k]] for k in mda]
    print(tabulate(data, headers))