# -*- coding: utf-8 -*-
"""
  run_parameters_init.py generated by WhatsOpt 1.9.4
"""
import numpy as np
from numpy import nan

def initialize(mda):

    mda['Ae'] = 1.5926
    mda['beta'] = 60
    mda['De'] = 1.424
    mda['Ds'] = 1.27
    mda['Dt'] = 1
    mda['FF'] = 0.95
    mda['f_safety'] = 1.5
    mda['g0'] = 9.80665
    mda['gamma'] = 1
    mda['k_sm'] = 1
    mda['Lfrust'] = 1.0
    mda['Lvehicle'] = 1
    mda['Mcarter'] = 1.0
    mda['Minsulation'] = 1.0
    mda['Mnozzle'] = 13
    mda['M_CaseBody'] = 1.0
    mda['M_CaseFrust'] = 1.0
    mda['M_CaseTop'] = 1.0
    mda['M_InsulationBody'] = 1.0
    mda['M_InsulationTop'] = 1.0
    mda['M_PL'] = 140
    mda['Pa'] = 26442
    mda['Pc'] = 5610000
    mda['Pe'] = 18327
    mda['R'] = 286.689655
    mda['rho'] = 1.6
    mda['rho_in'] = 850
    mda['rho_p'] = 1.85
    mda['Ru'] = 1
    mda['SF'] = 0.03
    mda['sigma'] = 800000000
    mda['Sint'] = 1
    mda['t'] = 1.0
    mda['tb'] = 75.3
    mda['Tc'] = 3440
    mda['theta_n'] = 15
    mda['zeta'] = 0.93630



if __name__ == "__main__":
    from tabulate import tabulate

    mda = {}
    initialize(mda)
    headers = ["parameter", "value"]
    data = [[k, mda[k]] for k in mda]
    print(tabulate(data, headers))