# -*- coding: utf-8 -*-
"""
  length_convergent_section_base.py generated by WhatsOpt 1.10.1
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 777


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from yaml import load, FullLoader
from openmdao.api import ExplicitComponent

class LengthConvergentSectionBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate LengthConvergentSection discipline """

    def __init__(self, **kwargs):
        super(LengthConvergentSectionBase, self).__init__(**kwargs)
        self._impl = None
        dockconf = path.join(path.dirname(__file__), ".whatsopt_dock.yml")
        if path.exists(dockconf):
            with open(dockconf) as dockfile:
                dock = load(dockfile, Loader=FullLoader)
                impl = dock.get("length_convergent_section")
                if impl:
                    module = import_module(impl['module'])
                    self._impl = getattr(module, impl['class'])()

    def setup(self):
        self.add_input('beta', val=1.0, desc='Nozzle convergent half angle')
        self.add_input('Ds', val=1.27, desc='Stage diameter')
        self.add_input('Dt', val=1.0, desc='Nozzle throat diameter')

        self.add_output('Lconv', val=np.ones((1,)), desc='Convergent nozzle section length')



        