# -*- coding: utf-8 -*-
"""
  length_divergent_section_base.py generated by WhatsOpt 1.9.4
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 777


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from yaml import load, FullLoader
from openmdao.api import ExplicitComponent

class LengthDivergentSectionBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate LengthDivergentSection discipline """

    def __init__(self, **kwargs):
        super(LengthDivergentSectionBase, self).__init__(**kwargs)
        self._impl = None
        dockconf = path.join(path.dirname(__file__), ".whatsopt_dock.yml")
        if path.exists(dockconf):
            with open(dockconf) as dockfile:
                dock = load(dockfile, Loader=FullLoader)
                impl = dock.get("length_divergent_section")
                if impl:
                    module = import_module(impl['module'])
                    self._impl = getattr(module, impl['class'])()

    def setup(self):
        self.add_input('De', val=1.424, desc='Nozzle exit diameter')
        self.add_input('Dt', val=1.0, desc='Nozzle throat diameter')
        self.add_input('Ru', val=1.0, desc='Longitudinal radius of the throat')
        self.add_input('theta_n', val=1.0, desc='Nozzle divergent half angle')

        self.add_output('Ldiv', val=np.ones((1,)), desc='Divergent nozzle section length')



        