# -*- coding: utf-8 -*-
"""
  mcase_base.py generated by WhatsOpt 1.9.3
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 777


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from yaml import load, FullLoader
from openmdao.api import ExplicitComponent

class McaseBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate Mcase discipline """

    def __init__(self, **kwargs):
        super(McaseBase, self).__init__(**kwargs)
        self._impl = None
        dockconf = path.join(path.dirname(__file__), ".whatsopt_dock.yml")
        if path.exists(dockconf):
            with open(dockconf) as dockfile:
                dock = load(dockfile, Loader=FullLoader)
                impl = dock.get("mcase")
                if impl:
                    module = import_module(impl['module'])
                    self._impl = getattr(module, impl['class'])()

    def setup(self):
        self.add_input('Dnozzle', val=1.0, desc='')
        self.add_input('Ds', val=1.27, desc='')
        self.add_input('f_safety', val=1.0, desc='')
        self.add_input('Lcase', val=np.ones((1,)), desc='')
        self.add_input('Lfrust', val=1.0, desc='')
        self.add_input('Mcarter', val=1.0, desc='')
        self.add_input('Minsulation', val=1.0, desc='')
        self.add_input('M_CaseBody', val=1.0, desc='')
        self.add_input('M_CaseFrust', val=1.0, desc='')
        self.add_input('M_CaseTop', val=1.0, desc='')
        self.add_input('M_InsulationBody', val=1.0, desc='')
        self.add_input('M_InsulationTop', val=1.0, desc='')
        self.add_input('Pc', val=1.0, desc='')
        self.add_input('rho', val=1.0, desc='')
        self.add_input('rho_in', val=1.0, desc='')
        self.add_input('sigma', val=1.0, desc='')
        self.add_input('t', val=1.0, desc='')

        self.add_output('Mcase', val=1.0, desc='')



        