# -*- coding: utf-8 -*-
"""
  mcase.py generated by WhatsOpt 1.9.3
"""
import numpy as np
from solid.mcase_base import McaseBase

class Mcase(McaseBase):
    """ An OpenMDAO component to encapsulate Mcase discipline """
		
    def compute(self, inputs, outputs):
        """ Mcase computation """
        if self._impl:
            # Docking mechanism: use implementation if referenced in .whatsopt_dock.yml file
            self._impl.compute(inputs, outputs)
        else:
                    
            outputs['Mcase'] = 1.0   

# Reminder: inputs of compute()
#   
#       inputs['Dnozzle'] -> shape: 1, type: Float    
#       inputs['Ds'] -> shape: 1, type: Float    
#       inputs['f_safety'] -> shape: 1, type: Float    
#       inputs['Lcase'] -> shape: 1, type: Float    
#       inputs['Lfrust'] -> shape: 1, type: Float    
#       inputs['Mcarter'] -> shape: 1, type: Float    
#       inputs['Minsulation'] -> shape: 1, type: Float    
#       inputs['M_CaseBody'] -> shape: 1, type: Float    
#       inputs['M_CaseFrust'] -> shape: 1, type: Float    
#       inputs['M_CaseTop'] -> shape: 1, type: Float    
#       inputs['M_InsulationBody'] -> shape: 1, type: Float    
#       inputs['M_InsulationTop'] -> shape: 1, type: Float    
#       inputs['Pc'] -> shape: 1, type: Float    
#       inputs['rho'] -> shape: 1, type: Float    
#       inputs['rho_in'] -> shape: 1, type: Float    
#       inputs['sigma'] -> shape: 1, type: Float    
#       inputs['t'] -> shape: 1, type: Float      
	
# To declare partial derivatives computation ...
# 
#    def setup(self):
#        super(Mcase, self).setup()
#        self.declare_partials('*', '*')  
#			
#    def compute_partials(self, inputs, partials):
#        """ Jacobian for Mcase """
#   
#       	partials['Mcase', 'Dnozzle'] = np.zeros((1, 1))
#       	partials['Mcase', 'Ds'] = np.zeros((1, 1))
#       	partials['Mcase', 'f_safety'] = np.zeros((1, 1))
#       	partials['Mcase', 'Lcase'] = np.zeros((1, 1))
#       	partials['Mcase', 'Lfrust'] = np.zeros((1, 1))
#       	partials['Mcase', 'Mcarter'] = np.zeros((1, 1))
#       	partials['Mcase', 'Minsulation'] = np.zeros((1, 1))
#       	partials['Mcase', 'M_CaseBody'] = np.zeros((1, 1))
#       	partials['Mcase', 'M_CaseFrust'] = np.zeros((1, 1))
#       	partials['Mcase', 'M_CaseTop'] = np.zeros((1, 1))
#       	partials['Mcase', 'M_InsulationBody'] = np.zeros((1, 1))
#       	partials['Mcase', 'M_InsulationTop'] = np.zeros((1, 1))
#       	partials['Mcase', 'Pc'] = np.zeros((1, 1))
#       	partials['Mcase', 'rho'] = np.zeros((1, 1))
#       	partials['Mcase', 'rho_in'] = np.zeros((1, 1))
#       	partials['Mcase', 'sigma'] = np.zeros((1, 1))
#       	partials['Mcase', 't'] = np.zeros((1, 1))        
