# -*- coding: utf-8 -*-
"""
  mcase.py generated by WhatsOpt 1.9.3
"""
import numpy as np
from solid.mcase_base import McaseBase

class Mcase(McaseBase):
    """ An OpenMDAO component to encapsulate Mcase discipline """
		
    def compute(self, inputs, outputs):
        """ Mcase computation """
        if self._impl:
            # Docking mechanism: use implementation if referenced in .whatsopt_dock.yml file
            self._impl.compute(inputs, outputs)
        else:

            Dnozzle = inputs['Dnozzle']
            Ds = inputs['Ds']
            f_safety = inputs['f_safety']
            Lcase = inputs['Lcase']
            Lfrust = inputs['Lfrust']
            Mcarter = inputs['Mcarter']
            Minsulation = inputs['Minsulation']
            M_CaseBody = inputs['M_CaseBody']
            M_CaseTop = inputs['M_CaseTop']
            M_InsulationBody = inputs['M_InsulationBody']
            M_InsulationTop = inputs['M_InsulationTop']
            Pc = inputs['Pc']
            rho = inputs['rho']
            rho_in = inputs['rho_in']
            sigma = inputs['sigma']
            t = inputs['t']

            t = ((Pc * Ds)/(2*sigma)) * f_safety

            M_CaseTop = rho * np.pi * t * (Ds/2)**2

            M_CaseBody = rho * np.pi * Lcase * ((Ds/2)**2 - (Ds/2 - t)**2)

            M_CaseFrust = ((rho * np.pi * Lfrust)/3) * (((Ds/2)**2 + (Ds/2) * (Dnozzle/4) + (Dnozzle/4)**2) - (((Ds/2) - t)**2) + ((Ds/2) - t) * ((Dnozzle/4) - t) + ((Dnozzle/4) - t)**2)

            M_InsulationTop = rho_in * np.pi * 0.003 * ((0.99*Ds) / 2)**2

            M_InsulationBody = rho_in * np.pi * Lcase * (((0.99 * Ds) / 2)**2 - (((0.99 * Ds)/2)**2 - (((0.99 * Ds)/2) - 0.003)**2))

            Mcarter = M_CaseBody + M_CaseTop + M_CaseFrust

            Minsulation = M_InsulationBody + M_InsulationTop
            
            Mcase = Mcarter + Minsulation
        
            outputs['Mcase'] = Mcase
        return outputs    

# Reminder: inputs of compute()
#   
#       inputs['Dnozzle'] -> shape: 1, type: Float    
#       inputs['Ds'] -> shape: 1, type: Float    
#       inputs['f_safety'] -> shape: 1, type: Float    
#       inputs['Lcase'] -> shape: 1, type: Float    
#       inputs['Lfrust'] -> shape: 1, type: Float    
#       inputs['Mcarter'] -> shape: 1, type: Float    
#       inputs['Minsulation'] -> shape: 1, type: Float    
#       inputs['M_CaseBody'] -> shape: 1, type: Float    
#       inputs['M_CaseFrust'] -> shape: 1, type: Float    
#       inputs['M_CaseTop'] -> shape: 1, type: Float    
#       inputs['M_InsulationBody'] -> shape: 1, type: Float    
#       inputs['M_InsulationTop'] -> shape: 1, type: Float    
#       inputs['Pc'] -> shape: 1, type: Float    
#       inputs['rho'] -> shape: 1, type: Float    
#       inputs['rho_in'] -> shape: 1, type: Float    
#       inputs['sigma'] -> shape: 1, type: Float    
#       inputs['t'] -> shape: 1, type: Float      
	
# To declare partial derivatives computation ...
# 
#    def setup(self):
#        super(Mcase, self).setup()
#        self.declare_partials('*', '*')  
#			
#    def compute_partials(self, inputs, partials):
#        """ Jacobian for Mcase """
#   
#       	partials['Mcase', 'Dnozzle'] = np.zeros((1, 1))
#       	partials['Mcase', 'Ds'] = np.zeros((1, 1))
#       	partials['Mcase', 'f_safety'] = np.zeros((1, 1))
#       	partials['Mcase', 'Lcase'] = np.zeros((1, 1))
#       	partials['Mcase', 'Lfrust'] = np.zeros((1, 1))
#       	partials['Mcase', 'Mcarter'] = np.zeros((1, 1))
#       	partials['Mcase', 'Minsulation'] = np.zeros((1, 1))
#       	partials['Mcase', 'M_CaseBody'] = np.zeros((1, 1))
#       	partials['Mcase', 'M_CaseFrust'] = np.zeros((1, 1))
#       	partials['Mcase', 'M_CaseTop'] = np.zeros((1, 1))
#       	partials['Mcase', 'M_InsulationBody'] = np.zeros((1, 1))
#       	partials['Mcase', 'M_InsulationTop'] = np.zeros((1, 1))
#       	partials['Mcase', 'Pc'] = np.zeros((1, 1))
#       	partials['Mcase', 'rho'] = np.zeros((1, 1))
#       	partials['Mcase', 'rho_in'] = np.zeros((1, 1))
#       	partials['Mcase', 'sigma'] = np.zeros((1, 1))
#       	partials['Mcase', 't'] = np.zeros((1, 1))        
