# -*- coding: utf-8 -*-
"""
  solid_base.py generated by WhatsOpt 1.10.1
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 777


import numpy as np
from numpy import nan

from openmdao.api import Problem, Group, ParallelGroup, IndepVarComp
from openmdao.api import NonlinearBlockGS
from openmdao.api import ScipyKrylov
from openmdao import __version__ as OPENMDAO_VERSION

from solid.propellants_mass import PropellantsMass
from solid.solid_motor_length import SolidMotorLength
from solid.migniter import Migniter
from solid.mcase import Mcase
from solid.solid_rocket_mass import SolidRocketMass
from solid.length_convergent_section import LengthConvergentSection
from solid.length_divergent_section import LengthDivergentSection
from solid.solid_rocket_length import SolidRocketLength










class SolidBase(Group):
    """ An OpenMDAO base component to encapsulate Solid MDA """
    def __init__(self, thrift_client=None, **kwargs):
        super(SolidBase, self). __init__(**kwargs)

        self.nonlinear_solver = NonlinearBlockGS() 
        self.nonlinear_solver.options['atol'] = 1.0e-10
        self.nonlinear_solver.options['rtol'] = 1.0e-10
        self.nonlinear_solver.options['err_on_non_converge'] = True
        self.nonlinear_solver.options['reraise_child_analysiserror'] = False

        self.linear_solver = ScipyKrylov()       
        self.linear_solver.options['atol'] = 1.0e-10
        self.linear_solver.options['rtol'] = 1.0e-10
        self.linear_solver.options['err_on_non_converge'] = True
        self.linear_solver.options['iprint'] = 1

    def setup(self): 

        self.add_subsystem('PropellantsMass', self.create_propellants_mass(), promotes=['Mp', 'prop_m', 'SF', 'tb'])
        self.add_subsystem('SolidMotorLength', self.create_solid_motor_length(), promotes=['Ds', 'FF', 'Lcase', 'Mp', 'rho_p'])
        self.add_subsystem('Migniter', self.create_migniter(), promotes=['Ds', 'Lcase', 'Migniter', 'Mp', 'rho_p'])
        self.add_subsystem('Mcase', self.create_mcase(), promotes=['Ds', 'f_safety', 'Lcase', 'Mcarter', 'Mcase', 'Minsulation', 'M_CaseBody', 'M_CaseTop', 'M_InsulationBody', 'M_InsulationTop', 'Pc', 'rho', 'rho_in', 'sigma', 't'])
        self.add_subsystem('SolidRocketMass', self.create_solid_rocket_mass(), promotes=['Mcase', 'Migniter', 'Mnozzle', 'Mp', 'M_SRM'])
        self.add_subsystem('LengthConvergentSection', self.create_length_convergent_section(), promotes=['beta', 'Ds', 'Dt', 'Lconv'])
        self.add_subsystem('LengthDivergentSection', self.create_length_divergent_section(), promotes=['De', 'Dt', 'Ldiv', 'Ru', 'theta_n'])
        self.add_subsystem('SolidRocketLength', self.create_solid_rocket_length(), promotes=['Lcase', 'Lconv', 'Ldiv', 'L_SRM'])

    def create_propellants_mass(self):
    	return PropellantsMass()
    def create_solid_motor_length(self):
    	return SolidMotorLength()
    def create_migniter(self):
    	return Migniter()
    def create_mcase(self):
    	return Mcase()
    def create_solid_rocket_mass(self):
    	return SolidRocketMass()
    def create_length_convergent_section(self):
    	return LengthConvergentSection()
    def create_length_divergent_section(self):
    	return LengthDivergentSection()
    def create_solid_rocket_length(self):
    	return SolidRocketLength()


# Used by Thrift server to serve disciplines
class SolidFactoryBase(object):
    @staticmethod
    def create_solid_propellants_mass():
    	return PropellantsMass()
    @staticmethod
    def create_solid_solid_motor_length():
    	return SolidMotorLength()
    @staticmethod
    def create_solid_migniter():
    	return Migniter()
    @staticmethod
    def create_solid_mcase():
    	return Mcase()
    @staticmethod
    def create_solid_solid_rocket_mass():
    	return SolidRocketMass()
    @staticmethod
    def create_solid_length_convergent_section():
    	return LengthConvergentSection()
    @staticmethod
    def create_solid_length_divergent_section():
    	return LengthDivergentSection()
    @staticmethod
    def create_solid_solid_rocket_length():
    	return SolidRocketLength()
