# -*- coding: utf-8 -*-
"""
  solid_rocket_length.py generated by WhatsOpt 1.9.3
"""
import numpy as np
from solid.solid_rocket_length_base import SolidRocketLengthBase

class SolidRocketLength(SolidRocketLengthBase):
    """ An OpenMDAO component to encapsulate SolidRocketLength discipline """
		
    def compute(self, inputs, outputs):
        """ SolidRocketLength computation """
        if self._impl:
            # Docking mechanism: use implementation if referenced in .whatsopt_dock.yml file
            self._impl.compute(inputs, outputs)
        else:
            Lcase = inputs['Lcase']
            Lconv = inputs['Lconv']
            Ldiv = inputs['Ldiv']

            L_SRM = Lcase + Ldiv + Lconv 

            outputs['L_SRM'] = L_SRM
        return outputs      

# Reminder: inputs of compute()
#   
#       inputs['Lcase'] -> shape: (1,), type: Float    
#       inputs['Lconv'] -> shape: (1,), type: Float    
#       inputs['Ldiv'] -> shape: (1,), type: Float      
	
# To declare partial derivatives computation ...
# 
#    def setup(self):
#        super(SolidRocketLength, self).setup()
#        self.declare_partials('*', '*')  
#			
#    def compute_partials(self, inputs, partials):
#        """ Jacobian for SolidRocketLength """
#   
#       	partials['L_SRM', 'Lcase'] = np.zeros((1, 1))
#       	partials['L_SRM', 'Lconv'] = np.zeros((1, 1))
#       	partials['L_SRM', 'Ldiv'] = np.zeros((1, 1))        
