# -*- coding: utf-8 -*-
"""
  avionics_mass.py generated by WhatsOpt 1.9.3
"""
import numpy as np
from mass.avionics_mass_base import AvionicsMassBase

class AvionicsMass(AvionicsMassBase):
    """ An OpenMDAO component to encapsulate AvionicsMass discipline """
		
    def compute(self, inputs, outputs):
        """ AvionicsMass computation """
        if self._impl:
            # Docking mechanism: use implementation if referenced in .whatsopt_dock.yml file
            self._impl.compute(inputs, outputs)
        else:
                    
            outputs['Mavionics'] = np.ones((1,))   

# Reminder: inputs of compute()
#   
#       inputs['Ds'] -> shape: (1,), type: Float    
#       inputs['Lvehicle'] -> shape: (1,), type: Float      
	
# To declare partial derivatives computation ...
# 
#    def setup(self):
#        super(AvionicsMass, self).setup()
#        self.declare_partials('*', '*')  
#			
#    def compute_partials(self, inputs, partials):
#        """ Jacobian for AvionicsMass """
#   
#       	partials['Mavionics', 'Ds'] = np.zeros((1, 1))
#       	partials['Mavionics', 'Lvehicle'] = np.zeros((1, 1))        
