# -*- coding: utf-8 -*-
"""
  interstage_length.py generated by WhatsOpt 1.9.4
"""
import numpy as np
from mass.interstage_length_base import InterstageLengthBase

class InterstageLength(InterstageLengthBase):
    """ An OpenMDAO component to encapsulate InterstageLength discipline """
		
    def compute(self, inputs, outputs):
        """ InterstageLength computation """
        if self._impl:
            # Docking mechanism: use implementation if referenced in .whatsopt_dock.yml file
            self._impl.compute(inputs, outputs)
        else:
            Lconv = inputs['Lconv']
            Ldiv = inputs['Ldiv']

            Linterstage = Lconv + Ldiv + 0.1
            
            outputs['Linterstage'] = Linterstage
        return outputs   

# Reminder: inputs of compute()
#   
#       inputs['Lconv'] -> shape: (1,), type: Float    
#       inputs['Ldiv'] -> shape: (1,), type: Float      
	
# To declare partial derivatives computation ...
# 
#    def setup(self):
#        super(InterstageLength, self).setup()
#        self.declare_partials('*', '*')  
#			
#    def compute_partials(self, inputs, partials):
#        """ Jacobian for InterstageLength """
#   
#       	partials['Linterstage', 'Lconv'] = np.zeros((1, 1))
#       	partials['Linterstage', 'Ldiv'] = np.zeros((1, 1))        
