# -*- coding: utf-8 -*-
"""
  characteristic_velocity_base.py generated by WhatsOpt 1.9.3
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 776


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from yaml import load, FullLoader
from openmdao.api import ExplicitComponent

class CharacteristicVelocityBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate CharacteristicVelocity discipline """

    def __init__(self, **kwargs):
        super(CharacteristicVelocityBase, self).__init__(**kwargs)
        self._impl = None
        dockconf = path.join(path.dirname(__file__), ".whatsopt_dock.yml")
        if path.exists(dockconf):
            with open(dockconf) as dockfile:
                dock = load(dockfile, Loader=FullLoader)
                impl = dock.get("characteristic_velocity")
                if impl:
                    module = import_module(impl['module'])
                    self._impl = getattr(module, impl['class'])()

    def setup(self):
        self.add_input('gamma_maj', val=np.ones((1,)), desc='Vandenkerckhove function')
        self.add_input('R', val=286.689655, desc='Specific gas constant')
        self.add_input('Tc', val=1.0, desc='Combustion chamber temperature')

        self.add_output('Cstar', val=np.ones((1,)), desc='Characteristic velocity')



        