# -*- coding: utf-8 -*-
"""
  characteristic_velocity.py generated by WhatsOpt 1.9.3
"""
import numpy as np
from propulsion.characteristic_velocity_base import CharacteristicVelocityBase

class CharacteristicVelocity(CharacteristicVelocityBase):
    """ An OpenMDAO component to encapsulate CharacteristicVelocity discipline """
		
    def compute(self, inputs, outputs):
        """ CharacteristicVelocity computation """
        if self._impl:
            # Docking mechanism: use implementation if referenced in .whatsopt_dock.yml file
            self._impl.compute(inputs, outputs)
        else:
                    
            outputs['Cstar'] = np.ones((1,))   

# Reminder: inputs of compute()
#   
#       inputs['gamma_maj'] -> shape: (1,), type: Float    
#       inputs['R'] -> shape: (1,), type: Float    
#       inputs['Tc'] -> shape: (1,), type: Float      
	
# To declare partial derivatives computation ...
# 
#    def setup(self):
#        super(CharacteristicVelocity, self).setup()
#        self.declare_partials('*', '*')  
#			
#    def compute_partials(self, inputs, partials):
#        """ Jacobian for CharacteristicVelocity """
#   
#       	partials['Cstar', 'gamma_maj'] = np.zeros((1, 1))
#       	partials['Cstar', 'R'] = np.zeros((1, 1))
#       	partials['Cstar', 'Tc'] = np.zeros((1, 1))        
