# -*- coding: utf-8 -*-
"""
  exhaust_velocity.py generated by WhatsOpt 1.9.3
"""
import numpy as np
from propulsion.exhaust_velocity_base import ExhaustVelocityBase

class ExhaustVelocity(ExhaustVelocityBase):
    """ An OpenMDAO component to encapsulate ExhaustVelocity discipline """
		
    def compute(self, inputs, outputs):
        """ ExhaustVelocity computation """
        if self._impl:
            # Docking mechanism: use implementation if referenced in .whatsopt_dock.yml file
            self._impl.compute(inputs, outputs)
        else:
                    
            outputs['Ve'] = np.ones((1,))   

# Reminder: inputs of compute()
#   
#       inputs['Cstar'] -> shape: (1,), type: Float    
#       inputs['C_F'] -> shape: (1,), type: Float      
	
# To declare partial derivatives computation ...
# 
#    def setup(self):
#        super(ExhaustVelocity, self).setup()
#        self.declare_partials('*', '*')  
#			
#    def compute_partials(self, inputs, partials):
#        """ Jacobian for ExhaustVelocity """
#   
#       	partials['Ve', 'Cstar'] = np.zeros((1, 1))
#       	partials['Ve', 'C_F'] = np.zeros((1, 1))        
