# -*- coding: utf-8 -*-
"""
  exhaust_velocity_base.py generated by WhatsOpt 1.10.1
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 776


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from yaml import load, FullLoader
from openmdao.api import ExplicitComponent

class ExhaustVelocityBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate ExhaustVelocity discipline """

    def __init__(self, **kwargs):
        super(ExhaustVelocityBase, self).__init__(**kwargs)
        self._impl = None
        dockconf = path.join(path.dirname(__file__), ".whatsopt_dock.yml")
        if path.exists(dockconf):
            with open(dockconf) as dockfile:
                dock = load(dockfile, Loader=FullLoader)
                impl = dock.get("exhaust_velocity")
                if impl:
                    module = import_module(impl['module'])
                    self._impl = getattr(module, impl['class'])()

    def setup(self):
        self.add_input('Cstar', val=np.ones((1,)), desc='Characteristic velocity')
        self.add_input('C_F', val=np.ones((1,)), desc='Thrust coefficient')

        self.add_output('Ve', val=np.ones((1,)), desc='Exhaust gas true exhaust velocity')



        