# -*- coding: utf-8 -*-
"""
  expansion_ratio.py generated by WhatsOpt 1.9.3
"""
import numpy as np
from propulsion.expansion_ratio_base import ExpansionRatioBase

class ExpansionRatio(ExpansionRatioBase):
    """ An OpenMDAO component to encapsulate ExpansionRatio discipline """
		
    def compute(self, inputs, outputs):
        """ ExpansionRatio computation """
        if self._impl:
            # Docking mechanism: use implementation if referenced in .whatsopt_dock.yml file
            self._impl.compute(inputs, outputs)
        else:
                    
            outputs['epsilon'] = np.ones((1,))   

# Reminder: inputs of compute()
#   
#       inputs['gamma'] -> shape: (1,), type: Float    
#       inputs['gamma_maj'] -> shape: (1,), type: Float    
#       inputs['Pc'] -> shape: (1,), type: Float    
#       inputs['Pe'] -> shape: (1,), type: Float      
	
# To declare partial derivatives computation ...
# 
#    def setup(self):
#        super(ExpansionRatio, self).setup()
#        self.declare_partials('*', '*')  
#			
#    def compute_partials(self, inputs, partials):
#        """ Jacobian for ExpansionRatio """
#   
#       	partials['epsilon', 'gamma'] = np.zeros((1, 1))
#       	partials['epsilon', 'gamma_maj'] = np.zeros((1, 1))
#       	partials['epsilon', 'Pc'] = np.zeros((1, 1))
#       	partials['epsilon', 'Pe'] = np.zeros((1, 1))        
