# -*- coding: utf-8 -*-
"""
  expansion_ratio_base.py generated by WhatsOpt 1.9.3
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 776


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from yaml import load, FullLoader
from openmdao.api import ExplicitComponent

class ExpansionRatioBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate ExpansionRatio discipline """

    def __init__(self, **kwargs):
        super(ExpansionRatioBase, self).__init__(**kwargs)
        self._impl = None
        dockconf = path.join(path.dirname(__file__), ".whatsopt_dock.yml")
        if path.exists(dockconf):
            with open(dockconf) as dockfile:
                dock = load(dockfile, Loader=FullLoader)
                impl = dock.get("expansion_ratio")
                if impl:
                    module = import_module(impl['module'])
                    self._impl = getattr(module, impl['class'])()

    def setup(self):
        self.add_input('gamma', val=1.22, desc='Flight path angle')
        self.add_input('gamma_maj', val=np.ones((1,)), desc='Vandenkerckhove function')
        self.add_input('Pc', val=5610000.0, desc='Combustion chamber pressure')
        self.add_input('Pe', val=18327.0, desc='Nozzle exit pressure')

        self.add_output('epsilon', val=np.ones((1,)), desc='Expansion ratio')



        