# -*- coding: utf-8 -*-
"""
  fonction_vandenkerckhove.py generated by WhatsOpt 1.9.3
"""
import numpy as np
from propulsion.fonction_vandenkerckhove_base import FonctionVandenkerckhoveBase

class FonctionVandenkerckhove(FonctionVandenkerckhoveBase):
    """ An OpenMDAO component to encapsulate FonctionVandenkerckhove discipline """
		
    def compute(self, inputs, outputs):
        """ FonctionVandenkerckhove computation """
        if self._impl:
            # Docking mechanism: use implementation if referenced in .whatsopt_dock.yml file
            self._impl.compute(inputs, outputs)
        else:
                    
            outputs['gamma_maj'] = np.ones((1,))   

# Reminder: inputs of compute()
#   
#       inputs['gamma'] -> shape: (1,), type: Float      
	
# To declare partial derivatives computation ...
# 
#    def setup(self):
#        super(FonctionVandenkerckhove, self).setup()
#        self.declare_partials('*', '*')  
#			
#    def compute_partials(self, inputs, partials):
#        """ Jacobian for FonctionVandenkerckhove """
#   
#       	partials['gamma_maj', 'gamma'] = np.zeros((1, 1))        
