# -*- coding: utf-8 -*-
"""
  specific_impulse_base.py generated by WhatsOpt 1.10.1
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 776


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from yaml import load, FullLoader
from openmdao.api import ExplicitComponent

class SpecificImpulseBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate SpecificImpulse discipline """

    def __init__(self, **kwargs):
        super(SpecificImpulseBase, self).__init__(**kwargs)
        self._impl = None
        dockconf = path.join(path.dirname(__file__), ".whatsopt_dock.yml")
        if path.exists(dockconf):
            with open(dockconf) as dockfile:
                dock = load(dockfile, Loader=FullLoader)
                impl = dock.get("specific_impulse")
                if impl:
                    module = import_module(impl['module'])
                    self._impl = getattr(module, impl['class'])()

    def setup(self):
        self.add_input('g0', val=9.80665, desc='Earth’s gravitational acceleration at sea level')
        self.add_input('Ve', val=np.ones((1,)), desc='Exhaust gas true exhaust velocity')

        self.add_output('Isp', val=np.ones((1,)), desc='Specific impulse')



        