# -*- coding: utf-8 -*-
"""
  throat_area_base.py generated by WhatsOpt 1.9.4
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 776


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from yaml import load, FullLoader
from openmdao.api import ExplicitComponent

class ThroatAreaBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate ThroatArea discipline """

    def __init__(self, **kwargs):
        super(ThroatAreaBase, self).__init__(**kwargs)
        self._impl = None
        dockconf = path.join(path.dirname(__file__), ".whatsopt_dock.yml")
        if path.exists(dockconf):
            with open(dockconf) as dockfile:
                dock = load(dockfile, Loader=FullLoader)
                impl = dock.get("throat_area")
                if impl:
                    module = import_module(impl['module'])
                    self._impl = getattr(module, impl['class'])()

    def setup(self):
        self.add_input('Ae', val=1.5926, desc='Nozzle exit area')
        self.add_input('epsilon', val=np.ones((1,)), desc='Expansion ratio')

        self.add_output('At', val=np.ones((1,)), desc='Throat area')



        