# -*- coding: utf-8 -*-
"""
  thrust_force_base.py generated by WhatsOpt 1.10.1
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 776


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from yaml import load, FullLoader
from openmdao.api import ExplicitComponent

class ThrustForceBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate ThrustForce discipline """

    def __init__(self, **kwargs):
        super(ThrustForceBase, self).__init__(**kwargs)
        self._impl = None
        dockconf = path.join(path.dirname(__file__), ".whatsopt_dock.yml")
        if path.exists(dockconf):
            with open(dockconf) as dockfile:
                dock = load(dockfile, Loader=FullLoader)
                impl = dock.get("thrust_force")
                if impl:
                    module = import_module(impl['module'])
                    self._impl = getattr(module, impl['class'])()

    def setup(self):
        self.add_input('Ae', val=1.5926, desc='Nozzle exit area')
        self.add_input('Pa', val=26442.0, desc='Ambient pressure')
        self.add_input('Pe', val=18327.0, desc='Nozzle exit pressure')
        self.add_input('prop_m', val=np.ones((1,)), desc='Propellantmass flow rate')
        self.add_input('Ve', val=np.ones((1,)), desc='Exhaust gas true exhaust velocity')
        self.add_input('zeta', val=0.9363, desc='Thrust correction factor')

        self.add_output('F_T', val=np.ones((1,)), desc='Thrust force')



        